# Generated by Django 6.0 on 2025-12-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_independant',
            field=models.BooleanField(default=False),
        ),
    ]
