# Generated by Django 6.0 on 2025-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_publisher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='editor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
