# Generated by Django 6.0 on 2025-12-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsletter_editor_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='editor_approved',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_published',
        ),
    ]
